version: '3.8'

services:
  # Наш бэкенд на Python (FastAPI)
  backend:
    build: ./backend
    container_name: portfolio-backend
    ports:
      - "8000:8000"
    restart: always

  # Наш фронтенд (веб-сервер Nginx с сайтом)
  portfolio:
    build: .
    container_name: my-portfolio-compose
    ports:
      - "8080:80"
    restart: always
    # Говорим Docker, что сайт должен запускаться только ПОСЛЕ того, как запустится бэкенд
    depends_on:
      - backend
