version: '3.8'

services:
  # Название нашего сервиса (может быть любым)
  portfolio:
    # Говорим Docker собрать образ из текущей папки (где лежит Dockerfile)
    build: .
    # Задаем имя контейнера
    container_name: my-portfolio-compose
    # Пробрасываем порты (компьютер : контейнер)
    ports:
      - "8080:80"
    # Опция автоматического перезапуска, если контейнер упадет
    restart: always
