name: CI Docker Build Check

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # Явно указываем стабильную версию Ubuntu, чтобы убрать предупреждение
    runs-on: ubuntu-24.04 

    steps:
      # Скачиваем код репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Проверяем сборку Docker-образа в одну простую команду
      - name: Build Docker image
        run: docker build -t portfolio-site .
